// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutApi.Data;

#nullable disable

namespace ScoutApi.Migrations
{
    [DbContext(typeof(ScoutApiContext))]
    [Migration("20250717145544_MovingEarnedRanks")]
    partial class MovingEarnedRanks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("GuardianScout", b =>
                {
                    b.Property<Guid>("GuardiansId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScoutsId")
                        .HasColumnType("TEXT");

                    b.HasKey("GuardiansId", "ScoutsId");

                    b.HasIndex("ScoutsId");

                    b.ToTable("GuardianScouts", (string)null);
                });

            modelBuilder.Entity("ScoutApi.Awards.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("ScoutApi.Awards.EarnedAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateEarned")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("ScoutId");

                    b.ToTable("EarnedAwards");
                });

            modelBuilder.Entity("ScoutApi.Guardians.Guardian", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimaryGuardian")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Guardians");
                });

            modelBuilder.Entity("ScoutApi.PhoneNumbers.PhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GuardianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.ToTable("PhoneNumber");
                });

            modelBuilder.Entity("ScoutApi.Scouts.Scout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("EarnedRanks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Scouts");
                });

            modelBuilder.Entity("GuardianScout", b =>
                {
                    b.HasOne("ScoutApi.Guardians.Guardian", null)
                        .WithMany()
                        .HasForeignKey("GuardiansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutApi.Scouts.Scout", null)
                        .WithMany()
                        .HasForeignKey("ScoutsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ScoutApi.Awards.EarnedAward", b =>
                {
                    b.HasOne("ScoutApi.Awards.Award", "Award")
                        .WithMany("EarnedAwards")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScoutApi.Scouts.Scout", "Scout")
                        .WithMany("EarnedAwards")
                        .HasForeignKey("ScoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Scout");
                });

            modelBuilder.Entity("ScoutApi.PhoneNumbers.PhoneNumber", b =>
                {
                    b.HasOne("ScoutApi.Guardians.Guardian", "Guardian")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("ScoutApi.Awards.Award", b =>
                {
                    b.Navigation("EarnedAwards");
                });

            modelBuilder.Entity("ScoutApi.Guardians.Guardian", b =>
                {
                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("ScoutApi.Scouts.Scout", b =>
                {
                    b.Navigation("EarnedAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
